spring:
  profiles:
    active: prod
  application:
    admin:
      enabled: true
    name: sba-service
  boot:
    admin:
      notify:
        slack:
          webhook-url: https://hooks.slack.com/services/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
          message: "*#{instance.registration.name}*/#{instance.id} is *#{event.statusInfo.status}* (${spring.profiles.active})"
        telegram:
          auth-token: 699959474:AAEEybcpbcpxDvR3bOVjAE4aOtMb4DAcJKk
          chat-id: -211478673
          message: "<strong>#{instance.registration.name}</strong>/#{instance.id} is <strong>#{event.statusInfo.status}</strong>  (${spring.profiles.active})"

management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: ALWAYS

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8081/eureka}
    should-unregister-on-shutdown: true
    registry-fetch-interval-seconds: 5
  instance:
    preferIpAddress: true
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
    lease-renewal-interval-in-seconds: 10
    metadata-map:
      startup: ${random.int}